### ISSUE TITLE
.types prop only works for first image?

### ISSUE THREAD

**Issue by philipaarseth** [piotrzdziarski/fslightbox-react#100]
Hi,

I'm having problems with "invalid file" and I cannot move the files to the same server, so I tried setting the types props, but it seems it only works for the first image.

``` javascript
<FsLightbox
      toggler={props.toggle}
      urls={["https://unsplash.com/photos/WWVD4wXRX38/download?force=true", "https://unsplash.com/photos/WWVD4wXRX38/download?force=true", "https://unsplash.com/photos/WWVD4wXRX38/download?force=true"]}
      slide={props.slideNr}
      types={ [ 
        'image'
      ] } 
    />
```

**Comment by philipaarseth** [comment]
I see now that it is an index system, is there no elegant way to set a type for the whole array?

**Comment by piotrzdziarski** [comment]
Currently not, gonna make **type** prop which will force type for every source :)

**Comment by philipaarseth** [comment]
Thanks! :)

**Comment by piotrzdziarski** [comment]
You can now download updated version, enjoy!

**Comment by philipaarseth** [comment]
Thanks! I'll check it out

**Comment by suprim12** [comment]
< FsLightbox
                    toggler={lightboxController.toggler}
                    sourceIndex={lightboxController.sourceIndex}
                    sources={items}
                    types={types}
                    disableLocalStorage={true}
                />

* Important Note( Both Should be equal / loop togther )
  sources:['https://unsplash.com/photos/','https://unsplash.com/photos']
  types:['image','image']

** Please make the documentation of the site fslightbox-react clear it sucks if you don't want any one to use remove it from MIT License
