### ISSUE TITLE
Can not install on mac 

### ISSUE THREAD

**Issue by sniperyork** [piotrzdziarski/fslightbox-react#108]
It seems like the plugin does not support MacOS?

I tried installing it through NPM and received the following error:

`npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64`

**Comment by phunguyenmurcul** [comment]
There's "dev" package inside dependencies in package.json, it requires inotify package.

**Comment by sniperyork** [comment]
would be appreciated if someone can provide a fix for the issue.

**Comment by piotrzdziarski** [comment]
I've published version without 'dev' package, can you try to install it now?

**Comment by sniperyork** [comment]
Thanks for fixing it, I got it installed with no issues now.
