### ISSUE TITLE
Vimeo support

### ISSUE THREAD

**Issue by sniperyork** [piotrzdziarski/fslightbox-react#111]
Hi,

I have been trying to figure out a way to incorporate Vimeo videos with the plugin but couldn't get it to work, is Vimeo currently not supported?

love this plugin, I've been playing around with it for 2 days and I'm loving it!

**Comment by piotrzdziarski** [comment]
Currently not, however I think about supporting it. Maybe not directly Vimeo, I'd rather go for adding an option to display completely custom sources from JSX.

**Comment by piotrzdziarski** [comment]
I've recently uploaded new version. Now you can display Vimeo videos. More: [https://fslightbox.com/react/documentation#basic-custom-sources](https://fslightbox.com/react/documentation#basic-custom-sources)
