### ISSUE TITLE
Can't input image urls of google firebase storage.

### ISSUE THREAD

**Issue by MingyuJeon** [piotrzdziarski/fslightbox-react#112]
**Version**
```
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "firebase": "^6.2.4",
    "@firebase/app": "^0.4.9",
    "@firebase/firestore": "^1.4.3",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
```
___
I tried to input image URLs of google firebase storage to sources of fsLightbox component.
However, it occurs error "Invalid files".

**Comment by murnieza** [comment]
What about mixed content types in `sources` array?

What should be done if we have a combination of images an youtube videos?
