### ISSUE TITLE
Taping on custom sources root element will close the lightbox

### ISSUE THREAD

**Issue by richarddd** [piotrzdziarski/fslightbox-react#122]
Another issue I found is when using custom sources the lightbox closes if you tap on the item needing presented. Looking through the sources reveals this:

```
if (!isSourceDownEventTarget) {
                self.hide();
            }
```

And the boolean is determined from:
```
if (e.target.classList.contains('fslightbox-source')) {
            isSourceDownEventTarget = true;
        }
```
Seems like the inner component in my div (the div has the `fslightbox-souece` class) is not picking up the click event. I could fix this by setting `pointer-events:all` on the div, but that causes the slider to freeze when dragging to change the slide.

See example here:
https://codesandbox.io/s/empty-breeze-e4fpc

**Comment by piotrzdziarski** [comment]
Just released new version with fix for that issue!
