### ISSUE TITLE
Lazy load pictures

### ISSUE THREAD

**Issue by qlerebours** [piotrzdziarski/fslightbox-react#123]
When the lightbox is opened, all the pictures are loaded at the same time.
I don't know which order is choosen to load the pictures, but when it seems that you have to wait all the pictures to be loaded to see the first one.

The best behaviour should be:
 - Load the picture to show and start loading the others in "background"
 - When we move to another picture, if the new current is loaded, show it, if it's not, show the loader
 - Load them in the right order

I don't know how it can be done, but it would be great.
Moreover, it would be awesome to have a way to set smaller images to load before, for progressive pictures loading (a.k.a medium loading).
There is a good component made with react for Progressive image loading: https://www.npmjs.com/package/react-progressive-image-loading

Thanks for the great work.
I'm waiting for the pro version btw :smiley:

**Comment by piotrzdziarski** [comment]
I'm glad you like it!

Indeed when lightbox opens all the pictures starts to load, but loading is asynchronous. Every source has it's own loader and it's displayed when the loading is complete, even if different sources are still being loaded.
When it comes to lazy loading - I was thinking about that :P, probably I will implement it in future.

**Comment by qlerebours** [comment]
Do you know if the pictures are loading in a specific order ?
