### ISSUE TITLE
ReferenceError: define is not defined

### ISSUE THREAD

**Issue by ducdev** [piotrzdziarski/fslightbox-react#82]
![image](https://user-images.githubusercontent.com/3524016/58434892-2bf8bb80-80e8-11e9-8874-d3d3aeda5c91.png)
Hi, this is happening when I tried with Nextjs. Any idea?

**Comment by piotrzdziarski** [comment]
Just released new version with SSR support. You can try it now :)

**Comment by ducdev** [comment]
Good to hear that, I'll try.
