### ISSUE TITLE
Config option for "thumbs"?

### ISSUE THREAD

**Issue by wle8300** [piotrzdziarski/fslightbox-react#92]
Hi Piotr (...or Peter?!)

Thank you for making such a slick ReactJS lightbox solution. I think it's the best one right now.

I have a question. I see that on your project webiste there are image thumbs, however I don't see a configuration option for this. Is there an undocumented way to display them?

![Screen Shot 2019-06-14 at 2 36 28 PM](https://user-images.githubusercontent.com/150245/59546837-5cfb2d80-8ee9-11e9-8011-613b611eb442.png)

**Comment by piotrzdziarski** [comment]
This is photo from pro Vanilla JS version. Pro React version is currently under development, it will have thumbs shown in this picture :)

**Comment by wle8300** [comment]
Oh got it! Thx for the quick reply :D
