### ISSUE TITLE
Making "slide" start at 0 (not 1)

### ISSUE THREAD

**Issue by wle8300** [piotrzdziarski/fslightbox-react#93]
Can you make `slide` start at 0 instead of 1?

```js
<FsLightbox
  toggler={ fn }
  slide={0} //<----- first image
  urls={[
    'images/first.jpg',
    'videos/second.mp4',
    'https://www.youtube.com/watch?v=xshEZzpS4CQ',
  ]}
/> 
```

This makes more sense because it's how arrays work.

**Comment by piotrzdziarski** [comment]
I'm not sure if it makes more sense, actually if there are 3 urls there are 3 slides(1,2,3), there is no 0 slide.
If this prop is supposed take an array index it should be renamed to something like: **slideIndex**.
Or I could make a new prop called like that and leave existing one. What you think about it?

**Comment by wle8300** [comment]
Yes I think adding a “slideIndex” prop would be a great solution!

I’m suggesting this because “carousel” components usually use 0 for the first slide. I know this is a “lightbox” but a “carousel” is similar paradigm.

**Comment by piotrzdziarski** [comment]
I've just released new version.
There are now two new props:
- source - you are chosing slide by passing full url
- sourceIndex - the thing we was talking about :)

You can check them in [documentation](https://fslightbox.com/react/documentation#basic-props).

**Comment by wle8300** [comment]
Yooo this looks great! Thx for improving an already great lightbox, Piotr!
