### ISSUE TITLE
fslightbox did not update new source

### ISSUE THREAD

**Issue by hoainam12k** [piotrzdziarski/fslightbox-react#99]
I'm using fslightbox for product gallery. After update **productdetail** state, new images are updated, but when click to show lightbox, it shows images of first product, not new update image.
Here is the code:
```
<div className="product-image">
  {productdetail.images.map((image, index) => (
    <a key={index} href="#" onClick={ () => this.openLightboxOnSource(image) }>
      <img src={image} alt="" />
    </a>
  ))}
  <FsLightbox
    toggler={ this.state.toggler }
    slide={ this.state.slide }
    sources={ productdetail.images }
    disableLocalStorage={true}
  />
</div>
```

**Comment by piotrzdziarski** [comment]
Hello, as described in documentation **sources** prop is not reactive. To inflict changes you need to remount component. I think using **key** will be best in your case (on every key prop update component is remounted):
```
<FsLightbox
  toggler={ this.state.toggler }
  slide={ this.state.slide }
  sources={ productdetail.images }
  disableLocalStorage={true}
  key={ productdetail }
/>
```

**Comment by hoainam12k** [comment]
yes, it works now. Thank you very much!

**Comment by qlerebours** [comment]
For information, I had the same problem but it gaves me a `Cannot read property zero of undefined` error.
I spent a lot of time to findout why because the error was really not comprehensive.
I think it would be better to introduce the `key` prop in the examples

**Comment by spanwair** [comment]
@piotrzdziarski finally some answer to my problem. Just wondering why is not implemented reaction into sources?

**Comment by mattkenefick** [comment]
This ticket shouldn't be closed.
